#3. Letra de música - Faça um programa que mostre na tela uma letra de música que você gosta (proibido letras do Justin Bieber)
print("letra da musica crazy da banda aerosmith")

print("Come here, baby")
print("You know you drive me up the wall")
print("The way you make good on all the nasty tricks you pull")
print("Seems like we're making up more than we're making love")
print("And it always seems you got something on your mind other than me")
print("Girl, you got to change your crazy ways")
print("You hear me?")
print("Say you're leaving on a seven thirty train")
print("And that you're heading out to Hollywood")
print("Girl, you been givin' me that line so many times")
print("It kinda gets like feeling bad looks good, yeah")
print("That kinda loving turns a man to a slave")
print("That kinda loving sends a man right to his grave")
print("I go crazy, crazy baby, I go crazy")
print("You turn it on")
print("Then you're gone")
print("Yeah, you drive me crazy")
print("Crazy, crazy for you baby")
print("What can I do, honey?")
print("I feel like the color blue")
print("You're packing up your stuff")
print("And talking like it's tough")
print("And trying to tell me that it's time to go, yeah!")
print("But, I know you ain't wearin' nothing underneath that over coat")
print("And it's all a show, yeah!")
print("That kinda loving")
print("Makes me wanna pull down the shade, yeah!")
print("That kinda loving, yeah")
print("Now I'm never, never, never gonna be the same")
print("I go crazy, crazy")
print("Baby, I go crazy")
print("You turn it on, then you're gone")
print("Yeah, you drive me crazy")
print("Crazy, crazy for you baby")
print("What can I do, honey?")
print("I feel like the color blue")
print("I'm losing my mind, girl")
print("'Cause I'm going cra")
print("I need your love, honey, yeah!")
print("I need your love")
print("Crazy, crazy, crazy for you baby")
print("I'm losing my mind, girl")
print("'Cause I'm going crazy")
print("Crazy, crazy, crazy for you baby")
print("You turn it on then, you're gone")
print("Yeah, you drive me")
print("Ooh, ooh, ooh, Ooh, ooh, ooh")
print("Ow, yeah, yeah, yeah, yeah, yeah")
print("Yeah, yeah, yeah, yeah, yeah")
print("Yeah, yeah, yeah, yeah")
print("Yeah, now baby, baby, baby, baby")